# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Mayank Jain
tagline:             Production Engineer at Facebook Inc.
#description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 https://mayankj08.github.io/
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Mayank Jain
  github:            mayankj08
  email:             jainmmayank@gmail.com
  linkedin:          mayankj08
  url:               https://twitter.com/mdo
  email:             mjain8@binghamton.edu
  gravatar_md5:      3d0369e6754d3b294801794a5f996b22

# Custom vars
version:             1.0.0

#Gems
plugins: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"

github:
  repo: https://github.com/mayankj08/

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
